import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class rbq{
    public static void main() {
      System.out.println("bussin' gyatt locked in frfr");
      System.out.println("Skibidi toliet is joever twin");
      System.out.println("SYBAU dih locked in frfr");
      System.out.println("Skibidi drip be yappin' cooked");
      System.out.println("sigma GOAT is joever L");
      System.out.println("Zesty drip touching grass no cap");
      System.out.println("Rizz aura vibe check cooked");
      System.out.println("SYBAU drip tweaking cooked");
      System.out.println("SYBAU sussy baka fanum taxed frfr");
      System.out.println("UWU sussy baka jestermaxxing no cap");
      System.out.println("goofy ahh 67 simp no cap");
      System.out.println("Skibidi gyatt sus moged ");
      System.out.println("Omega aura SDIYBTing caught in 4K");
      System.out.println("UWU dih rage-baiting L");
      System.out.println("Gigachad GOAT vibe check no shit");
      System.out.println("bussin' GOAT rage-baiting W");
      System.out.println("Omega fire vibe check caught in 4K");
      System.out.println("SYBAU bussi slapscaught in 4K");
      System.out.println("bussin' sussy baka tweaking L");
      System.out.println("bussin' 67 moged W");
      System.out.println("Zesty bussi vibe check twin");
      System.out.println("SYBAU 67 jestermaxxing moged ");
      System.out.println("sigma gyatt is joever L");
      System.out.println("sigma gyatt be yappin' no shit");
      System.out.println("SYBAU balls vibe check ratio");
      System.out.println("bussin' dih tweaking moged ");
      System.out.println("Rizz bussi sus moged ");
      System.out.println("Skibidi aura gooning moged ");
      System.out.println("Rizz 67 rage-baiting W");
      System.out.println("sigma balls slapsL");
      System.out.println("SYBAU toliet rage-baiting L");
      System.out.println("sigma dih washed moged ");
      System.out.println("Omega toliet sus twin");
      System.out.println("Zesty toliet tweaking ratio");
      System.out.println("Cringe dih tweaking KYS");
      System.out.println("SYBAU drip SDIYBTing frfr");
      System.out.println("Gigachad toliet washed KYS");
      System.out.println("Zesty 67 tweaking no cap");
      System.out.println("sigma sussy baka fanum taxed caught in 4K");
      System.out.println("UWU fire tweaking caught in 4K");
      System.out.println("Zesty 67 touching grass cooked");
      System.out.println("Skibidi aura be yappin' caught in 4K");
      System.out.println("goofy ahh toliet tweaking caught in 4K");
      System.out.println("Omega dih  lowkirksixsevenuinely moged KYS");
      System.out.println("goofy ahh fire simp frfr");
      System.out.println("sigma sussy baka looksmaxxing twin");
      System.out.println("sigma toliet sus twin");
      System.out.println("UWU gyatt moged no shit");
      System.out.println("Rizz gyatt rage-baiting ratio");
      System.out.println("SYBAU 67 touching grass L");
      System.out.println("Gigachad toliet  lowkirksixsevenuinely moged cooked");
      System.out.println("sigma drip slapsL");
      System.out.println("Skibidi bussi locked in bruh");
      System.out.println("Rizz toliet simp W");
  }
}