import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class rbq{
    public static void main() {
      System.out.println("sigma aura  lowkirksixsevenuinely moged no cap");
      System.out.println("UWU fire be yappin' no shit");
      System.out.println("SYBAU dih touching grass moged ");
      System.out.println("UWU bussi moged ratio");
      System.out.println("Omega 67 simp caught in 4K");
      System.out.println("sigma 67 washed caught in 4K");
      System.out.println("Skibidi drip  lowkirksixsevenuinely moged cooked");
      System.out.println("sigma GOAT washed L");
      System.out.println("bussin' aura  lowkirksixsevenuinely moged KYS");
      System.out.println("sigma aura slapsno cap");
      System.out.println("bussin' fire rage-baiting L");
      System.out.println("sigma 67 vibe check caught in 4K");
      System.out.println("bussin' GOAT looksmaxxing L");
      System.out.println("Rizz gyatt is joever moged ");
      System.out.println("bussin' balls  lowkirksixsevenuinely moged KYS");
      System.out.println("Gigachad bussi vibe check no cap");
      System.out.println("Zesty fire simp moged ");
      System.out.println("Skibidi GOAT simp KYS");
      System.out.println("goofy ahh fire rage-baiting moged ");
      System.out.println("Omega gyatt fanum taxed W");
      System.out.println("sigma GOAT moged no cap");
      System.out.println("UWU 67 fanum taxed moged ");
      System.out.println("bussin' aura slapsfrfr");
      System.out.println("Gigachad drip vibe check no cap");
      System.out.println("Skibidi toliet vibe check L");
      System.out.println("Rizz 67 rage-baiting KYS");
      System.out.println("Omega gyatt SDIYBTing no cap");
      System.out.println("Cringe gyatt SDIYBTing bruh");
      System.out.println("goofy ahh dih sus KYS");
      System.out.println("bussin' 67 sus W");
      System.out.println("Gigachad balls  lowkirksixsevenuinely moged KYS");
      System.out.println("Gigachad fire simp L");
      System.out.println("SYBAU gyatt slapscooked");
      System.out.println("goofy ahh aura is joever KYS");
      System.out.println("Cringe gyatt slapsfrfr");
      System.out.println("Rizz GOAT is joever twin");
      System.out.println("Skibidi balls simp frfr");
      System.out.println("Zesty balls fanum taxed bruh");
      System.out.println("Gigachad GOAT tweaking bruh");
      System.out.println("goofy ahh sussy baka fanum taxed frfr");
      System.out.println("SYBAU gyatt moged no cap");
      System.out.println("Zesty gyatt is joever W");
      System.out.println("Omega sussy baka tweaking caught in 4K");
      System.out.println("bussin' toliet be yappin' frfr");
      System.out.println("Omega bussi fanum taxed no shit");
      System.out.println("Rizz dih  lowkirksixsevenuinely moged L");
      System.out.println("Rizz toliet gooning L");
      System.out.println("Cringe bussi jestermaxxing W");
      System.out.println("UWU GOAT be yappin' no shit");
      System.out.println("bussin' dih tweaking moged ");
      System.out.println("SYBAU bussi gooning no cap");
      System.out.println("Cringe aura gooning ratio");
      System.out.println("SYBAU 67 is joever moged ");
      System.out.println("bussin' toliet tweaking twin");
      System.out.println("sigma bussi SDIYBTing cooked");
      System.out.println("Omega bussi be yappin' caught in 4K");
      System.out.println("Cringe drip is joever twin");
      System.out.println("Rizz sussy baka washed moged ");
      System.out.println("Gigachad balls SDIYBTing ratio");
      System.out.println("Zesty gyatt washed frfr");
      System.out.println("Skibidi GOAT SDIYBTing cooked");
      System.out.println("sigma fire moged bruh");
      System.out.println("Cringe sussy baka be yappin' twin");
      System.out.println("Omega 67 fanum taxed no cap");
      System.out.println("SYBAU gyatt vibe check caught in 4K");
      System.out.println("bussin' dih washed moged ");
      System.out.println("Cringe 67 tweaking no shit");
      System.out.println("Gigachad aura fanum taxed cooked");
      System.out.println("Gigachad balls gooning moged ");
      System.out.println("bussin' bussi gooning ratio");
      System.out.println("Skibidi drip looksmaxxing caught in 4K");
      System.out.println("Zesty GOAT gooning L");
      System.out.println("Rizz 67 fanum taxed KYS");
      System.out.println("Zesty gyatt washed no cap");
      System.out.println("Rizz toliet SDIYBTing moged ");
      System.out.println("Rizz GOAT rage-baiting moged ");
      System.out.println("bussin' drip moged cooked");
      System.out.println("Omega 67 tweaking moged ");
      System.out.println("goofy ahh bussi gooning frfr");
      System.out.println("Omega balls looksmaxxing no cap");
      System.out.println("Skibidi 67 sus ratio");
      System.out.println("Skibidi aura is joever ratio");
      System.out.println("Omega GOAT looksmaxxing no shit");
      System.out.println("Skibidi drip washed KYS");
      System.out.println("Rizz drip tweaking no cap");
      System.out.println("Cringe fire jestermaxxing twin");
      System.out.println("Skibidi aura be yappin' cooked");
      System.out.println("Rizz gyatt vibe check ratio");
      System.out.println("Gigachad fire rage-baiting no shit");
      System.out.println("Gigachad dih slapsno shit");
      System.out.println("UWU balls tweaking twin");
      System.out.println("Gigachad toliet gooning KYS");
      System.out.println("bussin' aura fanum taxed caught in 4K");
      System.out.println("Cringe toliet tweaking no cap");
      System.out.println("bussin' gyatt jestermaxxing L");
      System.out.println("bussin' toliet  lowkirksixsevenuinely moged moged ");
      System.out.println("Cringe toliet tweaking bruh");
      System.out.println("Gigachad toliet SDIYBTing KYS");
      System.out.println("Cringe sussy baka is joever frfr");
      System.out.println("bussin' gyatt be yappin' cooked");
      System.out.println("Zesty balls is joever frfr");
      System.out.println("Cringe fire touching grass caught in 4K");
      System.out.println("Rizz fire locked in no shit");
      System.out.println("Cringe fire  lowkirksixsevenuinely moged no shit");
      System.out.println("goofy ahh fire simp W");
      System.out.println("bussin' balls be yappin' no cap");
      System.out.println("Omega fire rage-baiting twin");
      System.out.println("Zesty sussy baka looksmaxxing frfr");
      System.out.println("bussin' GOAT locked in bruh");
      System.out.println("Omega gyatt looksmaxxing twin");
      System.out.println("bussin' bussi is joever W");
      System.out.println("Gigachad gyatt touching grass cooked");
      System.out.println("Zesty dih jestermaxxing no shit");
      System.out.println("Cringe GOAT jestermaxxing no cap");
      System.out.println("bussin' balls touching grass W");
      System.out.println("SYBAU drip tweaking W");
      System.out.println("UWU aura be yappin' ratio");
      System.out.println("SYBAU balls moged moged ");
      System.out.println("Omega drip locked in L");
      System.out.println("goofy ahh drip sus KYS");
      System.out.println("bussin' GOAT touching grass bruh");
      System.out.println("Cringe fire is joever twin");
      System.out.println("UWU gyatt is joever no cap");
      System.out.println("Rizz 67 rage-baiting bruh");
      System.out.println("Gigachad drip washed L");
      System.out.println("Rizz gyatt looksmaxxing cooked");
      System.out.println("UWU fire is joever twin");
      System.out.println("Zesty GOAT touching grass bruh");
      System.out.println("Skibidi toliet be yappin' ratio");
      System.out.println("SYBAU balls rage-baiting KYS");
      System.out.println("Gigachad balls looksmaxxing twin");
      System.out.println("SYBAU dih  lowkirksixsevenuinely moged caught in 4K");
      System.out.println("UWU 67 gooning caught in 4K");
      System.out.println("UWU dih fanum taxed caught in 4K");
      System.out.println("Gigachad drip touching grass moged ");
      System.out.println("Rizz dih slapsfrfr");
      System.out.println("Zesty gyatt vibe check W");
      System.out.println("sigma dih sus no cap");
      System.out.println("Rizz toliet simp L");
      System.out.println("SYBAU sussy baka looksmaxxing L");
      System.out.println("Zesty balls simp W");
      System.out.println("UWU sussy baka SDIYBTing frfr");
      System.out.println("Skibidi 67 locked in bruh");
      System.out.println("Omega balls fanum taxed ratio");
      System.out.println("UWU fire sus no shit");
      System.out.println("Gigachad drip fanum taxed ratio");
      System.out.println("sigma GOAT simp W");
      System.out.println("UWU drip vibe check W");
      System.out.println("Rizz drip be yappin' L");
      System.out.println("goofy ahh 67 sus ratio");
      System.out.println("SYBAU fire is joever L");
      System.out.println("Rizz fire moged caught in 4K");
      System.out.println("goofy ahh bussi sus frfr");
      System.out.println("Zesty gyatt vibe check twin");
      System.out.println("Skibidi gyatt washed frfr");
      System.out.println("Zesty balls be yappin' W");
      System.out.println("Rizz toliet jestermaxxing KYS");
      System.out.println("Omega fire touching grass cooked");
      System.out.println("SYBAU sussy baka touching grass KYS");
      System.out.println("UWU sussy baka be yappin' no cap");
      System.out.println("Cringe GOAT jestermaxxing cooked");
      System.out.println("Cringe fire washed L");
      System.out.println("goofy ahh bussi slapsbruh");
      System.out.println("sigma 67 rage-baiting ratio");
      System.out.println("Skibidi drip looksmaxxing KYS");
      System.out.println("Zesty balls  lowkirksixsevenuinely moged no shit");
      System.out.println("Zesty sussy baka touching grass no shit");
      System.out.println("Zesty fire gooning no cap");
      System.out.println("Zesty fire tweaking moged ");
      System.out.println("Cringe balls simp caught in 4K");
      System.out.println("Skibidi fire moged ratio");
      System.out.println("goofy ahh GOAT rage-baiting KYS");
      System.out.println("Gigachad aura fanum taxed no cap");
      System.out.println("bussin' bussi locked in twin");
      System.out.println("SYBAU dih tweaking ratio");
      System.out.println("Gigachad bussi tweaking cooked");
      System.out.println("Omega dih locked in cooked");
      System.out.println("SYBAU sussy baka looksmaxxing caught in 4K");
      System.out.println("Gigachad aura washed caught in 4K");
      System.out.println("UWU drip rage-baiting W");
      System.out.println("SYBAU 67 touching grass bruh");
      System.out.println("Cringe aura fanum taxed frfr");
      System.out.println("UWU gyatt looksmaxxing cooked");
      System.out.println("UWU gyatt  lowkirksixsevenuinely moged twin");
      System.out.println("goofy ahh drip slapsW");
      System.out.println("Omega fire sus KYS");
      System.out.println("sigma 67  lowkirksixsevenuinely moged moged ");
      System.out.println("Cringe toliet is joever bruh");
      System.out.println("Gigachad bussi is joever bruh");
      System.out.println("Zesty bussi simp KYS");
      System.out.println("Omega 67 SDIYBTing twin");
      System.out.println("sigma balls locked in no shit");
      System.out.println("UWU fire  lowkirksixsevenuinely moged moged ");
      System.out.println("sigma dih tweaking KYS");
      System.out.println("Omega sussy baka  lowkirksixsevenuinely moged ratio");
      System.out.println("UWU sussy baka locked in frfr");
      System.out.println("bussin' drip rage-baiting twin");
      System.out.println("SYBAU GOAT touching grass bruh");
      System.out.println("Gigachad drip  lowkirksixsevenuinely moged bruh");
      System.out.println("bussin' fire be yappin' no cap");
      System.out.println("Cringe GOAT SDIYBTing no shit");
      System.out.println("SYBAU bussi looksmaxxing KYS");
  }
}