import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class rbq{
    public static void main() {
      System.out.println("Gigachad toliet moged ratio");
      System.out.println("Cringe gyatt rage-baiting no shit");
      System.out.println("sigma balls jestermaxxing KYS");
      System.out.println("goofy ahh gyatt  lowkirksixsevenuinely moged W");
      System.out.println("UWU 67  lowkirksixsevenuinely moged bruh");
      System.out.println("Skibidi aura looksmaxxing bruh");
      System.out.println("goofy ahh gyatt vibe check KYS");
      System.out.println("sigma aura be yappin' no cap");
      System.out.println("Skibidi balls looksmaxxing twin");
      System.out.println("Rizz fire  lowkirksixsevenuinely moged no shit");
      System.out.println("SYBAU gyatt locked in W");
      System.out.println("Gigachad drip slapsfrfr");
      System.out.println("UWU aura vibe check L");
      System.out.println("sigma toliet sus twin");
      System.out.println("sigma 67 vibe check twin");
      System.out.println("Zesty fire looksmaxxing ratio");
      System.out.println("UWU gyatt looksmaxxing KYS");
      System.out.println("Omega balls sus moged ");
      System.out.println("Zesty 67 rage-baiting ratio");
      System.out.println("Gigachad drip sus bruh");
      System.out.println("Omega dih sus twin");
      System.out.println("Zesty 67 simp KYS");
      System.out.println("Omega drip locked in caught in 4K");
      System.out.println("goofy ahh gyatt simp cooked");
      System.out.println("goofy ahh drip SDIYBTing no shit");
      System.out.println("SYBAU dih jestermaxxing no shit");
      System.out.println("Gigachad fire  lowkirksixsevenuinely moged frfr");
      System.out.println("goofy ahh 67 slapsno cap");
      System.out.println("goofy ahh sussy baka simp L");
      System.out.println("Rizz dih slapsKYS");
      System.out.println("sigma 67  lowkirksixsevenuinely moged no shit");
      System.out.println("goofy ahh bussi vibe check L");
      System.out.println("Cringe GOAT SDIYBTing KYS");
      System.out.println("Omega sussy baka jestermaxxing moged ");
      System.out.println("Gigachad fire sus W");
      System.out.println("Omega gyatt slapscaught in 4K");
      System.out.println("Zesty GOAT rage-baiting moged ");
      System.out.println("Cringe balls moged no shit");
      System.out.println("Skibidi GOAT is joever no cap");
      System.out.println("Zesty toliet vibe check KYS");
      System.out.println("goofy ahh sussy baka is joever no cap");
      System.out.println("goofy ahh sussy baka locked in caught in 4K");
      System.out.println("goofy ahh bussi SDIYBTing ratio");
      System.out.println("Cringe gyatt  lowkirksixsevenuinely moged KYS");
      System.out.println("Gigachad sussy baka tweaking moged ");
      System.out.println("bussin' gyatt washed caught in 4K");
      System.out.println("Rizz dih fanum taxed ratio");
      System.out.println("sigma 67 tweaking KYS");
      System.out.println("Gigachad fire  lowkirksixsevenuinely moged bruh");
      System.out.println("Cringe gyatt looksmaxxing frfr");
      System.out.println("Zesty fire simp cooked");
      System.out.println("sigma 67 simp KYS");
      System.out.println("Omega bussi looksmaxxing moged ");
      System.out.println("Omega toliet looksmaxxing twin");
      System.out.println("bussin' 67 be yappin' W");
      System.out.println("bussin' 67 simp caught in 4K");
      System.out.println("bussin' balls slapsno shit");
      System.out.println("Cringe sussy baka  lowkirksixsevenuinely moged cooked");
      System.out.println("bussin' balls looksmaxxing twin");
      System.out.println("Rizz sussy baka tweaking no cap");
      System.out.println("bussin' GOAT vibe check bruh");
      System.out.println("Cringe bussi locked in bruh");
      System.out.println("Zesty aura locked in ratio");
      System.out.println("SYBAU sussy baka SDIYBTing W");
      System.out.println("Skibidi fire be yappin' frfr");
      System.out.println("Omega sussy baka tweaking ratio");
      System.out.println("Zesty fire  lowkirksixsevenuinely moged KYS");
      System.out.println("sigma 67 moged cooked");
      System.out.println("Omega balls simp no cap");
      System.out.println("goofy ahh toliet touching grass no cap");
      System.out.println("Skibidi drip touching grass caught in 4K");
      System.out.println("sigma balls fanum taxed ratio");
      System.out.println("Rizz drip moged ratio");
      System.out.println("sigma aura looksmaxxing W");
      System.out.println("sigma aura touching grass no cap");
      System.out.println("Omega toliet moged frfr");
      System.out.println("Zesty toliet vibe check W");
      System.out.println("UWU balls jestermaxxing bruh");
      System.out.println("sigma dih slapsratio");
      System.out.println("SYBAU 67 vibe check caught in 4K");
      System.out.println("bussin' sussy baka vibe check no shit");
      System.out.println("sigma GOAT jestermaxxing no shit");
      System.out.println("Rizz drip is joever no cap");
      System.out.println("Gigachad toliet touching grass no cap");
      System.out.println("goofy ahh sussy baka be yappin' KYS");
      System.out.println("Cringe balls fanum taxed caught in 4K");
      System.out.println("Cringe 67 moged L");
      System.out.println("SYBAU 67 simp caught in 4K");
      System.out.println("Gigachad toliet jestermaxxing W");
      System.out.println("SYBAU fire tweaking ratio");
      System.out.println("Gigachad dih gooning bruh");
      System.out.println("Cringe gyatt SDIYBTing twin");
      System.out.println("Omega gyatt moged no shit");
      System.out.println("Cringe dih gooning frfr");
      System.out.println("sigma GOAT locked in caught in 4K");
      System.out.println("bussin' dih simp bruh");
      System.out.println("Zesty 67 looksmaxxing no shit");
  }
}